version: '3.9'

services:
  webservice:
    build:
      context: ./webservice
    ports:
      - "5000:5000"
    volumes:
      - ./webservice/config.txt:/app/config.txt
    environment:
      - CONFIG_PATH=/app/config.txt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  load_balancer:
    build:
      context: ./load_balancer
    ports:
      - "8080:80"
    depends_on:
      - webservice
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
